---
# defaults file for collect
collect_endpoint_scheme: 'http'
collect_endpoint_host: 'localhost'
collect_endpoint_port: '8001'
collect_endpoint_path: 'api/v1/namespaces/metering/services/https:reporting-operator:http/proxy/api/v1/reports/get'
collect_format: 'csv'
collect_report_name: 'pod-cpu-usage'
collect_endpoint_params: '?name={{ collect_report_name }}&format={{ collect_format }}'
collect_archive_format: bz2
collect_archive_path: '/tmp'
collect_archive_name: korekuta
collect_delete_after: 'true'
collect_csv_uuid: '{{ 99999999999999999999 | random | to_uuid }}'
collect_clusterid: 'default-cluster'
collect_insights_client_cmd: '/usr/bin/insights-client'
collect_download_path: '/tmp/korekuta-collect'
