# OCP Usage Collector playbook for Insights Cost Management
---

- name: Run the OCP Usage Collector
  hosts: localhost
  connection: local
  roles:
    - {role: 'setup', tags: 'setup'}
    - {role: 'collect', tags: 'collect'}
