---
apiVersion: metering.openshift.io/v1alpha1
kind: ScheduledReport
metadata:
  name: hccm-openshift-usage-lookback
spec:
  generationQuery: "hccm-openshift-usage-lookback"
  inputs:
    - name: "ReportName"
      value: "hccm-openshift-usage"
  gracePeriod: "10m"  # wait for sub-query to finish
  schedule:
    period: "hourly"
  overwriteExistingData: true
